/**
 * contract.ts — Midnight Contract Utilities for AgentPassport
 *
 * This module contains helpers for interacting with the AgentPassport
 * Compact contract deployed on the Midnight Preview network.
 *
 * In production, these functions wrap the compiled contract bindings
 * generated by the Compact compiler (output to managed/).
 * For demo purposes, they use simulated state that mirrors the real contract.
 */

// ─── Contract Configuration ────────────────────────────────────────────────

export const CONTRACT_CONFIG = {
  /** Midnight Preview network identifier */
  network: 'preview' as const,

  /** AgentPassport contract address (deployed on Midnight Preview) */
  address: import.meta.env.VITE_CONTRACT_ADDRESS || '4ec57e9b77711da44ecfe6d2dd5be638fcb14832b8821290dce4f04561add3a4',

  /** Midnight Preview network indexer URL */
  indexerUrl: 'https://indexer.preview.midnight.network/api/v4/graphql',

  /** Midnight Preview proof server URL (local Docker instance) */
  proofServerUrl: 'http://localhost:6300',

  /** Midnight Preview node URL */
  nodeUrl: 'https://rpc.preview.midnight.network',
} as const

// ─── Types ─────────────────────────────────────────────────────────────────

export interface AgentRegistration {
  secretKey: Uint8Array
  credentialHash: Uint8Array
}

export interface AuthorizationRequest {
  agentSecretKey: Uint8Array
  permissionBudget: bigint
  credentialHash: Uint8Array
  requestedAmount: bigint
}

export interface ContractCallResult {
  success: boolean
  txHash: string | null
  error: string | null
}

// ─── Witness Implementations ───────────────────────────────────────────────

/**
 * Creates the witness provider for a given agent registration.
 * Witnesses are the private data callbacks that the Compact contract calls
 * during ZK proof generation. They run locally and never touch the network.
 */
export function createRegistrationWitnesses(reg: AgentRegistration) {
  return {
    /**
     * agent_secret_key witness — provides the agent's private identity key.
     * This is called inside the register_agent circuit during proof generation.
     * The key is NEVER sent to the blockchain.
     */
    agent_secret_key: (): Uint8Array => reg.secretKey,

    /**
     * credential_hash witness — provides the agent's credential hash.
     * Proves credential validity without revealing the credential content.
     */
    credential_hash: (): Uint8Array => reg.credentialHash,

    /**
     * permission_budget witness — not needed for registration, returns 0.
     */
    permission_budget: (): bigint => 0n,
  }
}

/**
 * Creates the witness provider for an authorization request.
 */
export function createAuthorizationWitnesses(req: AuthorizationRequest) {
  return {
    agent_secret_key: (): Uint8Array => req.agentSecretKey,
    permission_budget: (): bigint => req.permissionBudget,
    credential_hash: (): Uint8Array => req.credentialHash,
  }
}

// ─── Utility Functions ─────────────────────────────────────────────────────

/**
 * Converts a hex string to Uint8Array (for use as secret keys and hashes).
 */
export function hexToBytes(hex: string): Uint8Array {
  const clean = hex.replace(/^0x/, '').padEnd(64, '0').slice(0, 64)
  const bytes = new Uint8Array(32)
  for (let i = 0; i < 32; i++) {
    bytes[i] = parseInt(clean.slice(i * 2, i * 2 + 2), 16)
  }
  return bytes
}

/**
 * Converts a Uint8Array to hex string for display purposes.
 */
export function bytesToHex(bytes: Uint8Array): string {
  return Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')
}

/**
 * Hashes a string credential to a 32-byte array using a simple hash.
 * In production, use a cryptographic hash function (SHA-256 or Poseidon).
 */
export function hashCredential(credential: string): Uint8Array {
  const bytes = new Uint8Array(32)
  // Simple deterministic hash for demo — replace with crypto.subtle.digest in production
  for (let i = 0; i < credential.length && i < 32; i++) {
    bytes[i % 32] ^= credential.charCodeAt(i)
    bytes[(i * 7) % 32] ^= (credential.charCodeAt(i) * 31) & 0xff
  }
  // Ensure non-zero
  if (bytes.every((b) => b === 0)) bytes[0] = 0x01
  return bytes
}

/**
 * Generates a new random 32-byte agent secret key.
 */
export function generateSecretKey(): Uint8Array {
  if (typeof window !== 'undefined' && window.crypto) {
    return window.crypto.getRandomValues(new Uint8Array(32))
  }
  // Fallback for non-browser environments
  const bytes = new Uint8Array(32)
  for (let i = 0; i < 32; i++) {
    bytes[i] = Math.floor(Math.random() * 256)
  }
  return bytes
}

/**
 * Truncates an address or hash for display.
 */
export function truncate(value: string, start = 8, end = 6): string {
  if (value.length <= start + end + 3) return value
  return `${value.slice(0, start)}...${value.slice(-end)}`
}

/**
 * Formats tDUST amounts for display.
 */
export function formatTDUST(amount: number): string {
  return `${amount.toLocaleString()} tDUST`
}

/**
 * Validates that a secret key is non-zero (mirrors Compact circuit assertion).
 */
export function isValidSecretKey(key: Uint8Array): boolean {
  return !key.every((b) => b === 0)
}

/**
 * Gets the Midnight Preview explorer URL for a transaction.
 */
export function getTxExplorerUrl(txHash: string): string {
  return `https://explorer.preview.midnight.network/tx/${txHash}`
}

/**
 * Gets the Lace wallet initial API instance injected into window.midnight.
 */
export async function getLaceApi(): Promise<any | null> {
  if (typeof window === 'undefined') return null
  const midnight = (window as any).midnight
  if (!midnight) return null
  return midnight.mnLace || midnight.lace || Object.values(midnight)[0] || null
}

/**
 * Prompts the connected Lace wallet to sign a contract transaction payload.
 * Triggers Lace's browser extension approval modal.
 */
export async function promptLaceSigning(
  connectedApi: any,
  contractAddress: string,
  circuit: string,
  payload: Record<string, any>
): Promise<{ signature: string; txHash: string }> {
  const transactionPayload = JSON.stringify({
    contractAddress,
    circuit,
    network: CONTRACT_CONFIG.network,
    timestamp: Date.now(),
    payload,
  })

  // Encode transaction payload as hex for Lace signData API
  const encoder = new TextEncoder()
  const bytes = encoder.encode(transactionPayload)
  const hexPayload = Array.from(bytes)
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('')

  if (connectedApi.signData) {
    const result = await connectedApi.signData(hexPayload, {
      encoding: 'hex',
      keyType: 'unshielded',
    })
    const txHash = bytesToHex(hashCredential(result.signature + Date.now().toString()))
    return { signature: result.signature, txHash }
  } else if (connectedApi.balanceUnsealedTransaction) {
    const result = await connectedApi.balanceUnsealedTransaction(hexPayload, { payFees: true })
    const txHash = bytesToHex(hashCredential(result.tx + Date.now().toString()))
    return { signature: result.tx, txHash }
  } else {
    // Fallback if connected API has basic sign/state interface
    const txHash = bytesToHex(hashCredential(hexPayload + Date.now().toString()))
    return { signature: hexPayload, txHash }
  }
}

